### PR TITLE
New modern and responsive webdesign (like PHP.net website)

### PR DESCRIPTION
**Pull request by arnolem**
Website are now in HTML5
New PHP logo
New layout with responsive features
Replace font by Fira (like php.net)
Add H1 tag on the top of article
Modern table look and feel

### CODE REVIEW

**Comment by ramsey** [comment]
Two nit-picks on this:

1. It's a good practice to use a feature branch for new work and then send the pull request from your feature branch; this helps avoid odd merge commits as a result of your master being out of sync with the upstream master, and other junk commits
2. Do we need _all_ the font files you've provided? It doesn't look like you're using many of them in the style sheet. For example, you're using `font-weight: 400` on everything, and `font-weight: 500` on `h1`, so I don't think we need all the 700 font files or `@font-face` definitions. Also, you've defined Fira Mono, but it's not used in any of the styles. Did you intend to use that for `pre` and/or `code` tags?

**Comment by ramsey** [comment]
While you're in there, would you also update the header and footer to use the same header and footer that's on php.net? This has been on my to-do list for a long time. :smile:

Thanks!

### Header

php-header

### Footer

php-footer

**Comment by ramsey** [comment]
Looks great, by the way!

**Comment by arnolem** [comment]
1. I'm not very good with GitFlow. I would ask advice to a friend  :-)
2. I simply copied the same implementation that php.net to have the same possibilities even if not everything is used. We can load less if you think it's better (https://github.com/php/web-php/tree/master/fonts/Fira)
3. For the header, we are already close but I could repeat the same in a future version. Want the same menu to the documentation?
4. Thanks, I wanted to relax tonight 😏

**Comment by ramsey** [comment]
1. I'm not suggesting "GitFlow" necessarily. Using a separate branch makes it easier and keeps the commit log cleaner. For now, feel free to continue using your `master` branch, but learn about feature branches in pull requests for future contributions.
2. We can keep all the files. It's just overkill. That said, please update `<pre>` and `<code>` to use Fira Mono, since you've included it.
3. Yes, please. I'd like to have the same header and footer links that you see on php.net.
4. Relax. We're not in a rush here. :smile:

Here are some changes I'd like to see you work into this pull request. (In case you're not aware, all new commits you make to your master branch will also be added to this pull request automatically.)

These are changes that will make news.php.net feel like it fits right in to the standard php.net website. Feel free to ask any questions about these, and if you're not sure about what or how to implement any of this, let me know.

## Mailing Lists Homepage

manual-homepage

## Mailing List Table of Messages

manual-sub-page

## Mailing List Message

mailing-list-message

**Comment by arnolem** [comment]
Perfect! I would do that as soon as I have a little time.

**Comment by ramsey** [comment]
Thanks for doing this! It'll look great.

**Comment by arnolem** [comment]
I propose to add "news" to the PHP logo like the other sites.

image

Commit : https://github.com/php/web-news/pull/9/commits/3c20617c549aa9ba8669daa6330f825c834bc2d6

**Comment by ramsey** [comment]
I like it. What about “lists” instead of “news?” I know the domain is news.php.net, but it's the mailing lists, so the word “news” could be confusing to newcomers.

**Comment by arnolem** [comment]
Why not? I do not have an opinion on this.

image

Here's a preview, it's easy to change if you want

**Comment by ramsey** [comment]
Looks good.

**Comment by arnolem** [comment]
Just a little preview of the new menu 

image

**Comment by arnolem** [comment]
A simple searchbar 
image

**Comment by arnolem** [comment]
I propose to dissociate the readed links from the not readed links with a :visited style

image

**Comment by arnolem** [comment]
I propose to complety remove the sidebar 

image

**Comment by ramsey** [comment]
Both proposals are fine with me. Looks great!

**Comment by arnolem** [comment]
@ramsey it's pushed ;-)

**Comment by arnolem** [comment]
Just 2 others previews 👍 

image
image

**Comment by ramsey** [comment]
Love it! I’m away from my computer right now, but I’ll pull it down tomorrow, review, and merge it in. Thanks!

**Comment by arnolem** [comment]
Responsive preview :

responsive

responsive

**Comment by arnolem** [comment]
@ramsey I'm done for tonight, go to bed !

**Comment by ramsey** [comment]
Reviewed it, and it looks good. I'll go ahead and merge this PR in, and if you have any clean-up you want to apply, feel free to open another PR.

Thanks for doing all this!

**Comment by arnolem** [comment]
@ramsey In live, the PHP logo doesn't load

image

The server return the logo to text/plain

image

On the php.net server, the same logo is sent like an image, not a text

image

**Comment by ramsey** [comment]
I'm aware. I think the web server isn't sending the correct Content-Type header for it on news.php.net. I'm trying to find someone with access to the box to help.

**Comment by ramsey** [comment]
@bjori @Tyrael @derickr @rlerdorf It looks like you have access to the `pb1.php.net` system. Can you check the web server on that machine to see why news.php.net is sending back `text/plain` for these SVG images?

* http://news.php.net/i/php-logo.svg
* http://news.php.net/i/bg-texture-00.svg

Thanks!

**Comment by ramsey** [comment]
These image references have been updated to point to those served from php.net in the meantime.

**Pull request merged**
