### PR TITLE
Support running web-news locally with built-in webserver

### PR DESCRIPTION
**Pull request by ramsey**
This pull request allows one to run news.php.net locally, with the following command:

    NNTP_HOST=news.php.net php -S localhost:8080 .router.php

It also includes clean-up of some deprecated functionality.

### CODE REVIEW

**Comment by derickr** [comment]
LGTM

**Comment by Tyrael** [comment]
looks good

**Comment by salathe** [comment]
:+1:

**Comment by Tyrael** [comment]
let's see how does it work out in production.

**Pull request merged**
